# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zubber' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Zubber
  pod 'RNMobileCenter', '~> 0.3.0'
  pod 'MobileCenter', '~> 0.5.0'

  

  target 'ZubberTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Zubber-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Zubber-tvOS

  target 'Zubber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
